modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Death%20Backup"
logoFile="icon.png"

[[mods]]
modId="deathbackup"
version="3.6"
displayName="Death Backup"
displayURL="https://serilum.com/mod/death-backup"
authors="Rick South"
description='''Creates a backup of an inventory right before a player death, which can be loaded via a command.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.deathbackup]]
    modId="collective"
    mandatory=true
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deathbackup]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.2]"
    ordering="NONE"
    side="BOTH"
